# SPDX-License-Identifier: Apache-2.0
DEVICE=stm32f407vg
OPENCM3_TARGET=lib/stm32/f4
OPENOCD_CFG=board/stm32f4discovery.cfg
override DEVICES_DATA := ../common/devices.data

include ../common/opencm3.mk
