diff a/envs/fvp-corstone300-mps2/Makefile b/envs/fvp-corstone300-mps2/Makefile	(rejected hunks)
@@ -102,15 +102,13 @@ CFLAGS = -march=armv8.1-m.main+mve -mcpu=cortex-m55  \
         -I$(INC_DIR) -I$(INC_DIR_TEST)
 
 # Scatter files before/after preprocessing
-SCATTER_DEPENDENCIES=$(wildcard $(CMSIS_DEVICE)/Include/*.h)
-SCATTER_SRC_PRE=$(CMSIS_BASE)/Device/ARM/ARMCM55/Source/GCC/gcc_arm.ld
-SCATTER_SRC=$(BUILD_DIR)/gcc_arm.ld
+SCATTER_SRC=$(SRC_DIR)/gcc_arm.ld
 
 LDFLAGS = -march=armv8.1-m.main+mve -mcpu=cortex-m55 --entry=Reset_Handler \
           -T $(SCATTER_SRC) -specs=rdimon.specs
 
 endif # AC6 / GCC
 
 CMSIS_SRC_DIR=$(CMSIS_DEVICE)/Source
 C_SRC_FILES_PRE=$(wildcard $(SRC_DIR)/*.c) $(wildcard $(SRC_DIR)/*/*.c) $(wildcard $(SRC_DIR)/*/*/*.c)
 C_SRC_FILES=$(patsubst $(SRC_DIR)/%.c, %.c, $(C_SRC_FILES_PRE))
