# SPDX-License-Identifier: Apache-2.0

name: Setup nix
description: Setup nix

inputs:
  script:
    description: The script to be run in the nix shell
    required: false
  devShell:
    description: The name of the devShell
    required: true
    default: 'default'

runs:
  using: composite
  steps:
    - uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
    - name: Prepare nix dev shell
      shell: nix develop .#${{ inputs.devShell }} -c bash -e {0}
      run: |
    - name: Dependency check
      shell: nix develop .#${{ inputs.devShell }} -c bash -e {0}
      if: inputs.script != ''
      env:
        INPUT_SCRIPT: ${{ inputs.script }}
      run: eval "$INPUT_SCRIPT"
