name: Build everything
on:
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: nix develop -c bash -e {0}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Setup nix
      uses: ./.github/actions/setup-nix
      with:
        script: |
          arm-none-eabi-gcc --version
          qemu-system-arm --version
    - name: Make all
      run: |
        make -j$(nproc)
